name: Django CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Coverage
      run: |
        coverage run ./manage.py test
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@7d5dfa54903bd909319c580a00535b483d1efcf3
      uses: codecov/codecov-action@v1.0.14
      #with:
        # User defined upload name. Visible in Codecov UI
        #name: stregsystemet # optional?
        # Repository upload token - get it from codecov.io. Required only for private repositories
        #token: # optional
        # Path to coverage file to upload
        #file: .coverage # optional
        # Comma-separated list of files to upload
        #files: # optional
        # Directory to search for coverage reports.
        #directory: # optional
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        #flags: # optional
        # Write upload file to path before uploading
        #path_to_write_report: # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
        #env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        #fail_ci_if_error: # optional
        # Specify whether the Codecov output should be verbose
        #verbose: # optional
