name: Django CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run ./manage.py test
    - name: Coverage report
      run: |
        coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v1.0.14
